name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.deploy_k }}

      - name: Deploy to EC2
        run: ssh ubuntu@ec2-51-20-98-17.eu-north-1.compute.amazonaws.com 'bash -s' < deploy.sh
